name: TNTRunEvent
version: 1.0.0
api-version: 1.15
main: dev.nest.tntrun.Main
author: Nestirium
description: A plugin for the TNT Run event
commands:
  eventrmvall:
    aliases:
      - eventremoveall
  eventlst:
    aliases:
      - eventlist
  eventplay:
    aliases:
      - eventply
  eventrmv:
    aliases:
      - eventremove
  eventchk:
    aliases:
      - eventcheck
  eventstrt:
    aliases:
      - eventstart